name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: clone
      uses: actions/checkout@v4
    
    - name: install dependencies
      run: | 
        apt-get update
        apt-get install --yes freeglut3 freeglut3-dev  libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev build-essential libgl1-mesa-dev g++ make cmake libsdl2-dev libjpeg-dev qttools5-dev-tools qtbase5-dev qtmultimedia5-dev libboost-all-dev qt5-qmake

    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: make
      run: |
        cd build
        make -j$(nproc)
        ls -la
        
    #- name: qmake
    #  run: |
    #    qmake ..
    #    make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
